### ISSUE TITLE
It doesn't support mining Kaspa on NiceHash (wallet address issue).

### ISSUE THREAD

**Issue by i1itione** [bzminer/bzminer#122]
Now NiceHash support Kaspa algo., but I found BzMiner can't support it due to wallet address is BTC.

**Comment by bzminer** [comment]
Hey @i1itione , the beta supports nicehash. May release tomorrow. Beta can be found below

https://bzminer.com/downloads/bzminer_v12.1.1b4_windows.zip
https://bzminer.com/downloads/bzminer_v12.1.1b4_linux.tar.gz
