### ISSUE TITLE
14.1.0 not start using same flight sheet for 14.0.2 (watchdog issue)

### ISSUE THREAD

**Issue by wasarinta** [bzminer/bzminer#199]
**14.1.0 Radiant**
![image](https://user-images.githubusercontent.com/81989126/227712800-abf2dea2-7024-440e-8fcb-4e45431c374a.png)

**14.0.2 Radiant**
![image](https://user-images.githubusercontent.com/81989126/227712857-fdf01ea7-1e60-4115-8154-7c48a4986b4e.png)

***Flight sheet***
![image](https://user-images.githubusercontent.com/81989126/227713132-f4c1193d-acdd-4cea-9e1d-441469d787dd.png)

```"nvidia_only": true
"oc_core_clock_offset": "[[180,0],[150,0]]"
"oc_lock_core_clock": "[[1560,1200],[1455,1020]]"
"oc_memory_clock_offset": "[[0,1900],[0,1900]]"
"oc_lock_memory_clock": "[[810,8450],[810,7750]]"
"oc_fan_speed": "[[70,90],[70,90]]"
"zil_pool": "sg.crazypool.org:5005"
"zil_wallet": "zillwallet"

**Comment by bzminer** [comment]
Thanks for those details @wasarinta , I'm working on this issue right now and hope to have an update shortly
