### ISSUE TITLE
#URGENT, THERE IS A REDUCTION IN THE MH OF ZIL MINING, SEE THE ATTACHED IMAGES!

### ISSUE THREAD

**Issue by Aloprinha** [bzminer/bzminer#254]
BzMiner v15.2.1b6 (ZIL: 115,27mh)
GPU 3:0: zil OC set to [ Core Offset: 0mhz Locked Core: 1245mhz Mem Offset: 1800mhz Locked Mem: 0mhz]
![image](https://github.com/bzminer/bzminer/assets/137625101/fb52fcb7-165a-4b15-b3b1-e873ae4fb06b)

BzMiner v15.2.2b3 (ZIL: 104.20mh)
[zil] GPU 3:0: OC set to [ Core Offset: 0mhz Locked Core: 1245mhz Mem Offset: 1800mhz Locked Mem: 0mhz]
![image](https://github.com/bzminer/bzminer/assets/137625101/1dc52c8c-488b-4d78-93fa-b32266c6c214)

**Comment by Aloprinha** [comment]
BzMiner v15.3.0 (ZIL: 104.09mh)
[zil] GPU 3:0: OC set to [ Core Offset: 0mhz Locked Core: 1245mhz Mem Offset: 1800mhz Locked Mem: 0mhz]
![image](https://github.com/bzminer/bzminer/assets/137625101/f543b36d-d289-4f98-a07a-ba009826dcb5)

**Comment by bzminer** [comment]
Hey thanks @Aloprinha ! Sorry I didn't reply sooner, glad the last release did solve the issue though!
