### ISSUE TITLE
Zil Epoch 1

### ISSUE THREAD

**Issue by CamJava007** [bzminer/bzminer#256]
We need an ASAP update to support Zilliqa's latest update. Zil has moved to Epoch 1 and BZ Miner is no longer compatible. This should never have happened folks. This upgrade was long advertised.

**Comment by bzminer** [comment]
@CamJava007 thank you! New release should solve this issue

**Comment by bzminer** [comment]
> We need an ASAP update to support Zilliqa's latest update. Zil has moved to Epoch 1 and BZ Miner is no longer compatible. This should never have happened folks. This upgrade was long advertised.

Actually bz did support epoch 1 from the start, bz had a bug though that was not caught where it utilized the etc pipeline rather than eth pipeline so epoch was always divided by 2 internally

**Comment by bzminer** [comment]
Next epoch is in 3 years about so hopefully the transition is smoother

**Comment by CamJava007** [comment]
You are great. I apologize for giving you crap. From what I can see, you're actually one of the most "on top of things" dev's that I've run into. Thank you for the work that you do.

**Comment by bzminer** [comment]
Thank you @CamJava007 ! And it's all good, I completely understand the frustration with any downtime ~
