### ISSUE TITLE
Displays card # incorrect order

### ISSUE THREAD

**Issue by flash0222** [bzminer/bzminer#26]
![image](https://user-images.githubusercontent.com/28353525/150827148-daa9bc5a-882e-42b8-a78d-5ca12c1f5418.png)

Starts off with #10, then 11, then 12, then 1, then 2, etc
Be nice if it showed the cards in order 1,2,3,4,5,6,7,8,9,10,11,12

**Comment by bzminer** [comment]
@flash0222 this was a bug with an earlier version, this should be fixed in a 7.2 release

**Comment by flash0222** [comment]
You are right, closing
