### ISSUE TITLE
 <Warn> An error has occured openening settings file: config.txt

### ISSUE THREAD

**Issue by UselessGuru** [bzminer/bzminer#262]
```
 Loading settings from config.txt
 <Warn> An error has occured openening settings file: config.txt
 <Warn> The document root must not be followed by other values. (line: 228, 1)
}]
 ^
 <Warn> Default configuration will be used. Delete settings file and re-run to restore defaults.
```

What is happening here? I never touched the config.txt file in the miners directory.

**Comment by bzminer** [comment]
Hey @UselessGuru , could you delete config.txt and run again? It looks like it contains some invalid json, possibly a bug with some newly added options. If your running from command line you can add --nc 1 so it doesn't save the settings to config.txt

**Comment by UselessGuru** [comment]
> It looks like it contains some invalid json, possibly a bug with some newly added options. 

Most likely. I installed to a new directory

> you can add --nc 1

That did the trick.
