### ISSUE TITLE
17.0.1b1: API data for AMD miner is empty (KawPow only)

### ISSUE THREAD

**Issue by UselessGuru** [bzminer/bzminer#279]
17.0.1b1 has a new problem.
See attached [RX5700.txt](https://github.com/bzminer/bzminer/files/12796357/RX5700.txt), data from 'http://127.0.0.1:$($this.Port)/status'. Miner is running for a few minutes already.
17.0.0 was ok.

Edit: I can only see this issue with KawPow algorithm:
`BzMiner-v17.0.1b1\bzminer.exe -a rvn -p stratum+tcp://kawpow.auto.nicehash.com:9200 -w *******************************.************** --pool_password x -r *************--nc 1 --no_watchdog --http_enabled 1 --http_port 4001 --enable 9:0`

**Comment by bzminer** [comment]
Ah shoot, ok I'll take a look, thank you

**Comment by UselessGuru** [comment]
Can no longer reproduce the issue.
