### ISSUE TITLE
hashrate drop  v7.2.2

### ISSUE THREAD

**Issue by zulu1905** [bzminer/bzminer#33]
Hashrate dropped  ~ %3 with version 7.2.2

**Comment by bzminer** [comment]
hey @zulu1905 , there was a bug in the alephium algo, and by fixing it, reduced nvidia hashrate a little. it should be made up for in accepted shares and reduced rejected shares

**Comment by Maythecoffee** [comment]
> 
hi, what is about solo on node , will this 7.2.2 helps to find blocks also? comparing 7.16 which is stable version now.

**Comment by Maythecoffee** [comment]
> hey @zulu1905 , there was a bug in the alephium algo, and by fixing it, reduced nvidia hashrate a little. it should be made up for in accepted shares and reduced rejected shares

hi, what is about solo on node , will this 7.2.2 helps to find blocks also? comparing 7.16 which is stable version now.

**Comment by bzminer** [comment]
@Maythecoffee that's a risk. You get slightly higher hashrate with pre 7.2.2 versions, but you have a risk of finding an invalid share. In my opinion it would be best to update for solo, because it would be disappointing to find an invalid block instead of a valid block. the risk is roughly .5 to 1%

**Comment by Maythecoffee** [comment]
> @Maythecoffee that's a risk. You get slightly higher hashrate with pre 7.2.2 versions, but you have a risk of finding an invalid share. In my opinion it would be best to update for solo, because it would be disappointing to find an invalid block instead of a valid block. the risk is roughly .5 to 1%

clear, thx

**Comment by zulu1905** [comment]
@bzminer 

In addition, I would like to point out for those who complain about the disconnection problem, I think that the disconnection problems are not related to bzminer, there were disconnections in woolypolly(i was mining woolypooly), but currently there is no disconnection problem in herominers(now i am mining on herominers). Everything is visible in the picture.
![aaaaa](https://user-images.githubusercontent.com/21012254/151706216-bd1f53bf-c0b1-432b-ae3e-09ac7c66c64a.PNG)
.

**Comment by bzminer** [comment]
This should be fixed in v7.2.5 and higher, feel free to reopen if you believe this is not the case
