### ISSUE TITLE
BzMiner 7.2.3 - --disable option does not work with AMD APU

### ISSUE THREAD

**Issue by blackmennewstyle** [bzminer/bzminer#39]
I'm running the following command line `/home/ceedii/bzminer_v7.2.3_linux/bzminer -a alph -p stratum+tcp://pool.sg.woolypooly.com:3106 -w ******************************************.calypso --http_enabled 1 --http_address 192.168.0.19 --http_port 4450 --http_password calypso --nc 1 --disable 10:0 --no_watchdog` on a GNU/Linux Ubuntu 20.04.3 using **bzminer_v7.2.3_linux_cuda_tk.tar.gz**, it's an all AMD GPU rig with a AMD Ryzen 3200G (Picasso APU), i specified `--disable 10:0` which is the UID of the AMD APU and unfortunately according to your HTTP API, it's not ignored by the miner and it is actually used for mining
![Screenshot_2022-01-29_01-52-41](https://user-images.githubusercontent.com/4682874/151643000-d380f925-559e-4f0c-95a5-7da53665393b.jpg)
The following interface is my own Python3 Django web application, developed for my mining farm, which uses the BzMiner HTTP API `http://192.168.0.19:4450/status?pass=calypso` in order to get the all the mining statistics.

**Comment by bzminer** [comment]
You did the command correctly to disable the apu. It should work, so I will test that command with my apu and report back here

**Comment by bzminer** [comment]
Turns out this was actually a bug. this should be fixed in next release

**Comment by blackmennewstyle** [comment]
I saw your comment about the `--nc` option in the latest release `7.2.4` and i can confirm that not using that option with `7.2.3` actually disables the APU as expected and the issue is definitely fixed with `7.2.4` :)
