### ISSUE TITLE
cuda_tk vs standard version

### ISSUE THREAD

**Issue by Maythecoffee** [bzminer/bzminer#49]
what is the difference between cudat_tk version and standard one? i ma asking because on new drivers LHR lock works too often if you mining ETH, so older 470.74 470.86 are preferable, so what is the difference between tk and standard ones and in hive and rave which version of your miner is installed?

I mean is there any difference in performance between 11.5 and 11.4?

**Comment by bzminer** [comment]
hey @Maythecoffee the cuda_tk version is for exactly the reason you mentioned, for rigs that you don't want to upgrade the nvidia driver. minimum version cuda_tk supports is 460.27.03 (cuda 11.2)

hive and rave use the non cuda_tk from my understanding.

Also there is no difference in performance, other than any optimizations the different driver versions may have
