### ISSUE TITLE
Transport endpoint is already connected

### ISSUE THREAD

**Issue by i8088** [bzminer/bzminer#51]
_Warn_ Connection to stratum+tcp://eth.2miners.com:2020 failed: . Transport endpoint is already connected. Transport endpoint is already connected. Transport endpoint is already connected. Transport endpoint is already connected. Transport endpoint is already connected. Transport endpoint is already connected. Transport endpoint is already connected. Transport endpoint is already connected

**Comment by bzminer** [comment]
not sure what the problem here is, i'll look into this though and let you know if i find anything

**Comment by payazo915** [comment]
I fixed this my entering the miners setup and changing the URL to ethstratum+tcp://us-eth.2miners.com:2020

**Comment by bzminer** [comment]
@i8088, @payazo915 is right, there's a bug in the latest version with the auto protocol selection. for 2miners, the protocol you should use is ethstratum, not stratum. bzminer SHOULD find the correct stratum automatically but its a bug, which will be fixed in the next version

**Comment by bzminer** [comment]
This had to do with how 2miners was responding to the wrong protocol. 2miners uses ethstratum. This is fixed in the latest version, v8.0.2
