### ISSUE TITLE
Unable to mine ETH

### ISSUE THREAD

**Issue by lzy2009** [bzminer/bzminer#53]
I can't mine ETH, from the 7.2.2 version to the current 7.2.4 version is not OK, please ask me where the setting is wrong
![微信图片_20220202231529](https://user-images.githubusercontent.com/96769059/152182123-2845c67c-1ac8-498d-8199-d3e914758d72.png)
![微信图片_20220202231743](https://user-images.githubusercontent.com/96769059/152182339-2726e6d4-8a1b-4874-ba97-f965df0978fb.png)
?

**Comment by zerox-20** [comment]
There is not support in BZminer yet, you are using a 3080ti which has LHR.

**Comment by bzminer** [comment]
I'm sorry i missed this. the auto protocol detection code was broken and should be fixed in the latest bzminer version (v8.0.2). Please reopen this issue if this is not the case
