### ISSUE TITLE
mining.authorize json error 

### ISSUE THREAD

**Issue by altinsoft** [bzminer/bzminer#56]
Hi

mining.authorize =>> {"id":3,"method":"mining.authorize","params":["1Bug41RJ1FWQUumtRpAHma8E8C9RB2UdenZQNNAEgDg59.RIG1.RIG1"]}

Example : 1Bug32RJ1FWQUumtRpAHma8E8C9RB2UdenZQNNAXgDg59.RIG1.RIG1

wallet_name.Rig_name.Rig_name (this wrong !)

The json data Bzminer sends to the pool is wrong!

Rig name is sent 2 times.

https://wiki.alephium.org/Alephium-Stratum.html

Here is the original template information.

**Comment by bzminer** [comment]
@altinsoft someone else had mentioned this and i had tried to reproduce but wasn't able to. i'll look into that again and see why its doing this, hopefully get it fixed for next release

**Comment by bzminer** [comment]
I've found the issue finally, so it'll be fixed in next release
