### ISSUE TITLE
ETC+ALPH hashrate not tuned/stable

### ISSUE THREAD

**Issue by BitMaci** [bzminer/bzminer#58]
Using this dual mining mode, ALPH hashrate is high, while ETC one is about 66% less than usual.

Example GTX 1650 dual mining ETC+ALPH (lolMiner): ETC 14.5 MH - ALPH 270 MH
Example GTX 1650 dual mining ETC+ALPH (BZMiner): ETC 5 MH - ALPH 280 MH

Thank you

**Comment by bzminer** [comment]
hey @BitMaci , the next release of bzminer will have some updates to dual mining

By default,  the latest version of bzminer does "alternate" mining, which means that while one algo is mining, the other algo is paused. It flips between each algo, which allows you to set overclocks per algo. By default, the timings are 5 seconds mining for the first algo, and 15 seconds for the second algo. You can change these settings in the most recent version of bzminer using the lhr_mine_ms parameter, which is [5000, 15000] by default

these timings were chosen based on VERY limited testing of lhr on 3080ti, where lhr triggered after about 5 seconds, and took about 15 seconds to reset

Dual mining in bzminer was designed to get more out of lhr cards. It is not currently able to get over 100% coins like some of the other miners. This is a feature i will be looking into later though

**Comment by BitMaci** [comment]
Hello, many thanks for the alternate mining explanation and for the next releases with dual mining updates, I'll be waiting for that because I have a FHR card!

**Comment by BitMaci** [comment]
Not solved in next release.
