### ISSUE TITLE
v8 (non tk) still requires libnvrtc.so.11.2

### ISSUE THREAD

**Issue by tymoteuszrogalewski** [bzminer/bzminer#59]
Something is mixed.

v8 (non tk version) should work with 11.5 and requires this version in theory but in real it looks like this:

running show this:
root@simplemining:/bzminer-v8.0.0-cuda11.2# ./bzminer -a ethash -w $walletETH.$rigName -p stratum+tcp://us1.ethermine.org:4444 stratum+tcp://us2.ethermine.org:4444
./bzminer: error while loading shared libraries: libnvrtc.so.11.2: cannot open shared object file: No such file or directory

ldd bzminer also gives error that this lib in 11.2 version is required.

When I include those files:
libcudart.so
libcudart.so.11.0
libcudart.so.11.2.146
libnvrtc-builtins.so
libnvrtc-builtins.so.11.2
libnvrtc-builtins.so.11.2.142
libnvrtc.so
libnvrtc.so.11.2
libnvrtc.so.11.2.142
...then it works ok...but only on rigs with NV driver that is compatible with CUDA 11.5 :)

the big mix ;-)

PS I didnt test with including cuda 11.5 libraries and...do not know if its necessery when it works with 11.2 libs files.

**Comment by PriyanshuNaredi** [comment]
How To Fix It , I Am New To Linux

**Comment by bzminer** [comment]
hey guys, sorry about that, i ran into driver issues right before releasing, and it seems that it broke the dependencies in the latest version of bzminer. i will attempt to get this sorted out in the next release

**Comment by tymoteuszrogalewski** [comment]
For me works ok as I described above: installed NV driver 495.46 that is CUDA 11.5 compatible (on older NV driver the miner do not mining at all), and cuda libraries (as above listed) CUDA 11.2 packages (as binary bzminer requires this with ldd) ;-)
Closing issue for now. Thanks for reply.

**Comment by bzminer** [comment]
thanks @tymoteuszrogalewski for getting back with what worked , i'll try to get the dependency issues figured out for this next release

**Comment by tymoteuszrogalewski** [comment]
I wanted to just note something.
ldd talks about 11.2 version of libnvrtc.so.11.2 requirements even that you talk that 8.0.0 is compiled with cuda 11.5

This may be answer for that "strange/mix" issue:

```
cd /usr/local/cuda-11.5/lib64
ls -l | grep libnvrtc
lrwxrwxrwx 1 root root        25 Mar  9 10:30 libnvrtc-builtins.so -> libnvrtc-builtins.so.11.5
lrwxrwxrwx 1 root root        28 Mar  9 10:30 libnvrtc-builtins.so.11.5 -> libnvrtc-builtins.so.11.5.50
-rwxr-xr-x 1 root root   6985608 Mar  9 10:27 libnvrtc-builtins.so.11.5.50
-rw-r--r-- 1 root root   7006948 Mar  9 10:27 libnvrtc-builtins_static.a
lrwxrwxrwx 1 root root        16 Mar  9 10:29 libnvrtc.so -> libnvrtc.so.11.2
lrwxrwxrwx 1 root root        19 Mar  9 10:29 libnvrtc.so.11.2 -> libnvrtc.so.11.5.50
-rwxr-xr-x 1 root root  45092752 Mar  9 10:27 libnvrtc.so.11.5.50
-rw-r--r-- 1 root root  70176288 Mar  9 10:27 libnvrtc_static.a
```

as you can see - the required lib named libnvrtc.so.11.2 is a link to phisical library file named libnvrtc.so.11.5.50
...thats mean that CUDA developers do some mix in file names heh...
probably there are not (many?) incompatible changes in 11.5 comparing to 11.2 and the main library file still contains 11.2 in file name ;P

hope this helps ;-)

**Comment by bzminer** [comment]
thanks @tymoteuszrogalewski , i'm trying to investigate this right now, i wonder if my issue is because i've installed cuda 11.2 over my 11.5 installation, where previously i had done it the other way around. 11.5 is only required because its the first cuda version that contains static runtime compilation libraries for cuda. ideally i would only require 11.2, so going to look at this again and see if i can do something to only need 11.2, then i wouldn't need two versions of bzminer (one being the cuda_tk)
