### ISSUE TITLE
Browser gui not scaling properly

### ISSUE THREAD

**Issue by DeeDeeRanged** [bzminer/bzminer#6]
Rig window scales nicely in Firefox
Pools/Devices and Pool Solutions do not scale properly.
Console does scale nicely.

Would be nice to fix it so that the Pools/Devices and Solutions window.
![Screenshot at 2021-11-20 00-01-45](https://user-images.githubusercontent.com/12376567/142701977-641a4714-beef-404f-aa4b-2aacbd1b4bf0.png)
s 

Thanks in advance.

**Comment by bzminer** [comment]
hey @DeeDeeRanged ! I will be updating the gui in two releases, I will be sure that it scales properly in that release, thank you!

**Comment by bzminer** [comment]
hey @DeeDeeRanged , this issue is fixed in the latest (v5.1) version of BzMiner

https://github.com/bzminer/bzminer/releases/tag/v5.1

![image](https://user-images.githubusercontent.com/83083846/147267304-8357dd99-1638-4d83-a41a-0ebabd01cd4b.png)
