### ISSUE TITLE
8.0.1  Connecting with ethstratum failed

### ISSUE THREAD

**Issue by tymoteuszrogalewski** [bzminer/bzminer#62]
8.0.0 works ok, and 8.0.1 failed.

second problem is that:
./bzminer --help gives help output and on the end...segfault.

**Comment by bzminer** [comment]
hi @tymoteuszrogalewski , whats your config? which pool and coin? nvidia or amd? windows/linux?

**Comment by tymoteuszrogalewski** [comment]
sorry about missing "description". 8.0.2 works ok.
