### ISSUE TITLE
cannot mine ixian

### ISSUE THREAD

**Issue by Jorgelote** [bzminer/bzminer#68]
I have been trying to mine ixian but there is always an error of connection with every pool, 
Please let me know how to solve it, 
Thanks

**Comment by bzminer** [comment]
Hey @Jorgelote , I'm assuming your on hive? I think hive automatically adds stratum in front of the url. Your urls to the pools should look like http://poolurl:port

**Comment by Jorgelote** [comment]
i am on windows, and i could make it work, thanks for the quick answer anyway
