### ISSUE TITLE
Request: Addition of Equihash 125,4 Algorithm 

### ISSUE THREAD

**Issue by gorgarp** [bzminer/bzminer#79]
Hello! I'd like to request Equihash 125,4 be added. Our project, Flux (Runonflux.io), is a GPU minable coin and is one of the fastest growing projects in the space. Additionally, we are considered one of the main 4 likely replacements for ETH hashrate, post merge.

Please reach out to us on dicord.io/runonflux, if you would like to discuss this. We know that your group can make a large impact and we'd love to work with you.

Current implementations are gminer, miniz, lolminer.

**Comment by bzminer** [comment]
hey @gorgarp ! i'll add that to my list! i haven't decided which algo i'll add next, but i'll be taking equihash into consideration. i've had multiple requests for it now

**Comment by gorgarp** [comment]
Hello, It looks like the latest added Ergo and Kaspa. Any thoughts as to 125,4 timeline?

**Comment by gorgarp** [comment]
Hello,

Post merge we've increased our hashrate from 1.25 MSol/s up to 10MSol/s. Would love to know where this stands. As we continue this growth, we could use more quality mining software in the mix.

**Comment by bzminer** [comment]
Hi @gorgarp ! I'm actually finishing it up in bzminer right now, I expect to have it done in the next day or two and will release!

**Comment by bzminer** [comment]
Also I appreciate you pinging me about this, sometimes things get lost in my list of things to do but flux has been at the top for a while now and I've finally got the time to get it in! I'll post back here after I release

**Comment by bzminer** [comment]
Btw @gorgarp , I haven't been super good about watching the GitHub issues, but I'm quite active on discord, you can ping me there and get a response probably much faster, either way is good though!

**Comment by gorgarp** [comment]
Works for me bud. I'll find the discord so we can have open comms if needed. I can also get you in touch with any team members, should the need arise in the future.
