### ISSUE TITLE
Suggestion: Mentioning updates @github 

### ISSUE THREAD

**Issue by Kostas-13** [bzminer/bzminer#89]
Wouldn't be better for every version update of BZminer to mention what changed?
Took me a while to find that at the official web page xD

**Comment by bzminer** [comment]
Hey @Kostas-13 , thank you! Actually the changes on the official site should match the release notes on the GitHub releases page. Is there somewhere else you'd like to see the changeling?

**Comment by Kostas-13** [comment]
Nop just that. Should be helpful, specially for noobies like me @bz  thx :)
